#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: redeploy the MeleeVS pairing server (pairing.joyastick.com).
#
#   server/pairing/deploy/redeploy-wizard.sh
#
# Wraps deploy.sh with the checks around it: the right code, a reachable VM,
# passing tests, and afterwards the one thing that must never change (the
# public key every shipped client has compiled in) plus a live probe from
# this machine. Remembers the VM and SSH key in your home folder, not the
# repo.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
ENV_FILE="$HOME/.config/meleevs/pairing-deploy.env"
mkdir -p "$(dirname "$ENV_FILE")"
DEFAULT_VM="ubuntu@40.233.68.38"
DEFAULT_KEY="$HOME/.ssh/meleevs_pairing"
# What clients have compiled in (CMakeLists.txt): the address they dial and
# the key the server's answers must be signed with.
EXPECTED_KEY=$(sed -n 's/^set(MELEE_PAIRING_KEY "\([0-9a-f]\{64\}\)".*/\1/p' "$ROOT/CMakeLists.txt")
PUBLIC_ADDR=$(sed -n 's/^set(MELEE_PAIRING_SERVER "\([^"]*\)".*/\1/p' "$ROOT/CMakeLists.txt")

banner "Redeploy the MeleeVS pairing server"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight: tools and the code being shipped"
missing=()
for tool in go ssh scp git; do
  command -v "$tool" >/dev/null 2>&1 || missing+=("$tool")
done
if (( ${#missing[@]} )); then
  warn "missing: ${missing[*]} (Go: winget install GoLang.Go; ssh/scp come with Git for Windows)"
  exit 1
fi
say "Tools: go, ssh, scp, git all found."
if [[ -z "$EXPECTED_KEY" || -z "$PUBLIC_ADDR" ]]; then
  warn "could not read MELEE_PAIRING_KEY / MELEE_PAIRING_SERVER from CMakeLists.txt"
  exit 1
fi
say "Clients dial ${BOLD}$PUBLIC_ADDR${RESET} and trust key ${DIM}$EXPECTED_KEY${RESET}"
printf '\n'
say "Server code that will be shipped (from this checkout):"
note "  branch: $(git -C "$ROOT" rev-parse --abbrev-ref HEAD)"
note "  last server change: $(git -C "$ROOT" log -1 --format='%h %s' -- server/pairing)"
if [[ -n "$(git -C "$ROOT" status --porcelain -- server/pairing)" ]]; then
  warn "server/pairing has uncommitted changes; they would be deployed too:"
  git -C "$ROOT" status --short -- server/pairing | sed 's/^/      /'
fi
printf '\n'
confirm "Ship this server code?" || { say "Stopped. Check out the branch you want and re-run."; exit 0; }

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "VM: reach it and read the live server"
note "The VM is Oracle Cloud 'MeleeVS-MatchmakingServer'. Enter keeps the saved or default value."
while :; do
  ask PAIRING_VM "SSH target [default $DEFAULT_VM]:"
  PAIRING_VM=${PAIRING_VM:-$DEFAULT_VM}
  ask PAIRING_SSH_KEY "SSH key file [default $DEFAULT_KEY]:"
  PAIRING_SSH_KEY=${PAIRING_SSH_KEY:-$DEFAULT_KEY}
  PAIRING_SSH_KEY=${PAIRING_SSH_KEY/#\~/$HOME}
  if [[ ! -f "$PAIRING_SSH_KEY" ]]; then
    warn "no key file at $PAIRING_SSH_KEY (it was made on the laptop and never copied elsewhere)"
    confirm "Try another path?" && continue
    exit 1
  fi
  say "Connecting to $PAIRING_VM ..."
  if live=$(ssh -i "$PAIRING_SSH_KEY" -o BatchMode=yes -o ConnectTimeout=15 "$PAIRING_VM" \
      'sudo /usr/local/bin/pairing -check 127.0.0.1:27720 &&
       sudo /usr/local/bin/pairing -key /var/lib/private/pairing/server.key -pubkey' 2>&1); then
    break
  fi
  warn "could not reach the server over SSH:"
  printf '%s\n' "$live" | sed 's/^/      /'
  say "If the VM is stopped, start it in the Oracle console (Compute > Instances)."
  open_url "https://cloud.oracle.com/compute/instances"
  confirm "Try again?" || exit 1
done
write_env PAIRING_VM "$PAIRING_VM"
write_env PAIRING_SSH_KEY "$PAIRING_SSH_KEY"
LIVE_KEY=$(printf '%s\n' "$live" | tail -n1)
say "Live server: $(printf '%s\n' "$live" | head -n1)"
if [[ "$LIVE_KEY" == "$EXPECTED_KEY" ]]; then
  say "${GREEN}✓${RESET} its key matches the one clients trust"
else
  warn "its key is $LIVE_KEY, not the one clients trust. Stop and investigate before deploying."
  confirm "Continue anyway?" || exit 1
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Test the server code locally"
say "Running go vet and go test in server/pairing ..."
if ! (cd "$ROOT/server/pairing" && go vet ./... && go test ./...); then
  warn "tests failed: nothing was deployed"
  exit 1
fi
say "${GREEN}✓${RESET} tests pass"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Deploy"
say "deploy.sh cross-compiles the server, installs it and its systemd units,"
say "keeps the existing signing key, and restarts the service."
warn "Players searching right now lose their place in the queue for ~2 s"
warn "(their games keep trying through the DHT and re-queue by themselves)."
confirm "Deploy to $PAIRING_VM now?" || { say "Stopped before deploying. Nothing changed."; exit 0; }
DEPLOY_LOG=$(mktemp)
if ! "$ROOT/server/pairing/deploy/deploy.sh" "$PAIRING_VM" -i "$PAIRING_SSH_KEY" 2>&1 | tee "$DEPLOY_LOG"; then
  warn "deploy.sh failed (output above). The service may be on the old or new binary: re-run to retry."
  exit 1
fi
DEPLOYED_KEY=$(sed -n 's/^public key: \([0-9a-f]\{64\}\).*/\1/p' "$DEPLOY_LOG" | tail -n1)
rm -f "$DEPLOY_LOG"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify from outside"
if [[ "$DEPLOYED_KEY" == "$EXPECTED_KEY" ]]; then
  say "${GREEN}✓${RESET} deployed server key is unchanged (clients still trust it)"
else
  warn "deployed server reported key '${DEPLOYED_KEY:-none}', expected $EXPECTED_KEY"
  warn "Shipped clients will ignore this server until that is fixed."
fi
say "Probing $PUBLIC_ADDR from this machine, as a player's game would ..."
PROBE_DIR=$(mktemp -d)
(cd "$ROOT/server/pairing" && go build -o "$PROBE_DIR/pairing" .)
set +e
"$PROBE_DIR/pairing" -probe "$PUBLIC_ADDR" -expect "$EXPECTED_KEY" 2>&1 | sed 's/^/      /'
probe=${PIPESTATUS[0]}
set -e
rm -rf "$PROBE_DIR"
case $probe in
  0) say "${GREEN}✓${RESET} live, signed by the trusted key, and taking two topics per search" ;;
  3) warn "live, but still the OLD server (no two-topic support): the new binary did not take" ;;
  *) warn "the probe failed (output above): check 'sudo journalctl -u pairing' on the VM" ;;
esac
note "In a game log, a Direct Connect now shows: pairing: server can wait on two topics per search"
pause

finish
